name: python-workshop
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.23.4
  - matplotlib=3.6.2
  - netcdf4=1.6.2 
  - ipython=8.6.0
  - notebook=6.5.2
  - cartopy=0.18.0
  - pandas=1.5.1
  - s3fs=2022.11.0
  - xarray=2022.11.0
  - metpy=1.3.1
